### ISSUE TITLE
Error when starting external-auth-server

### ISSUE THREAD

**Issue by mukundv18** [travisghansen/external-auth-server#145]
# node src/server.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'jsonpath'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/external-auth-server/src/assertion/index.js:1:74)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by mukundv18** [comment]
Should a JSON file be created? I followed the same steps mentioned @ https://github.com/travisghansen/external-auth-server#source

**Comment by travisghansen** [comment]
If you're running from source you need to `npm i` in the top-level dir before anything else to install all the dependencies.

**Comment by mukundv18** [comment]
Thanks @travisghansen !
