### ISSUE TITLE
Traefik setup with Google ends in 503

### ISSUE THREAD

**Issue by jeroenroodnat** [travisghansen/external-auth-server#27]
I have setup Traefik and eas based on the Howto. I have the authentication with Google oauth working. Request comes back to eas server, it then forwards to the original URL but that fails with a 503 code.

The original URL webserver POD does not get the request. For some reason the 503 is generated by eas server. It looks like the succesfull authentication is not recognized.

```
{"message":"starting verify pipeline","level":"info","service":"external-auth-server"}
{"service":"external-auth-server","level":"info","message":"starting verify for plugin: oauth2"}
{"service":"external-auth-server","level":"info","message":"redirecting to original resource: https://<original-URL>/"}
{"service":"external-auth-server","level":"info","message":"end verify pipeline with status: 302"}
{"message":"starting verify pipeline","level":"info","service":"external-auth-server"}
{"service":"external-auth-server","level":"info","message":"starting verify for plugin: oauth2"}
{"level":"error","service":"external-auth-server","message":"Cannot read property 'data' of undefined","stack":"TypeError: Cannot read property 'data' of undefined\n    at OauthPlugin.prepare_token_headers (/home/eas/app/src/plugin/oauth/index.js:790:30)\n    at OauthPlugin.verify (/home/eas/app/src/plugin/oauth/index.js:670:24)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"service":"external-auth-server","level":"info","message":"end verify pipeline with status: 503"}
```

How can I debug the error and figure out the solution?

**Comment by jeroenroodnat** [comment]
In my use-case I want Google to handle authentication for users inside and outside of our domain. I will then assert if certain users can access my app using eas assertions. I am unsure if oidc allows me to do this in Google. Google oidc seems to be limited to users in my gsuite domain only.

**Comment by jeroenroodnat** [comment]
great thanks for the feedback

**Comment by jeroenroodnat** [comment]
confirmed that it works now.
